### ISSUE TITLE
MacBook 10,1

### ISSUE THREAD

**Issue by Ricotan-Linus** [hyrorre/BootCampKeyFix#1]
Macbook 10,1+Windows10 1909にて動作確認。SPIキーボードで動作を確認したことになります。

**Comment by Ricotan-Linus** [comment]
ブログに取り上げて頂いたこと感謝します。
一日使ってみた感想としてひらがなキーにする場合の方が当方にとって利便性が高いと思います。もしよろしければご検討いただけませんでしょうか。

**Comment by hyrorre** [comment]
情報提供ありがとうございます。

かなキーへのマッピングも考えましたが、
IME等の設定で同じことが実現できるので、
今回はブログの修正はしないでおこうと思います。
